In [562]:
# pip install pandas
# pip install matplotlib
# pip install sqlite3
# pip install kaggle
# move kaggle.json file into ~/.kaggle (mac) or C:\Users<Windows-username>.kaggle\kaggle.json (windows)

import kaggle
import pandas as pd
import numpy as np
import matplotlib as plt
import sqlite3 as db

dataset = "rohanrao/formula-1-world-championship-1950-2020"

kaggle.api.dataset_download_files(dataset, path='./', unzip=True)

print(f"Dataset {dataset} downloaded successfully!")

Dataset URL: https://www.kaggle.com/datasets/rohanrao/formula-1-world-championship-1950-2020
Dataset rohanrao/formula-1-world-championship-1950-2020 downloaded successfully!


In [563]:
results_df = pd.read_csv('results.csv')
qualifying_df = pd.read_csv('qualifying.csv')
lap_times_df = pd.read_csv('lap_times.csv')
pit_stops_df = pd.read_csv('pit_stops.csv')
driver_standings_df = pd.read_csv('driver_standings.csv')
races_df = pd.read_csv('races.csv')
constructors_df = pd.read_csv('constructors.csv')
status_df = pd.read_csv('status.csv')

In [564]:

results_df.drop(['number', 'positionText', 'time', 'rank', 'fastestLap', 'fastestLapTime', 'fastestLapSpeed', 'laps', 'points', 'positionOrder', 'grid'], axis=1, inplace=True)

results_df.rename(columns={'position': 'final_position'}, inplace=True)

results_df['final_position'] = results_df['final_position'].replace('\\N', np.nan)
results_df.final_position = pd.to_numeric(results_df.final_position, errors='coerce')
results_df.milliseconds = pd.to_numeric(results_df.milliseconds, errors='coerce')
print(results_df.dtypes)
results_df.head()

resultId            int64
raceId              int64
driverId            int64
constructorId       int64
final_position    float64
milliseconds      float64
statusId            int64
dtype: object


resultId  raceId  driverId  constructorId  final_position  milliseconds  \
0         1      18         1              1             1.0     5690616.0   
1         2      18         2              2             2.0     5696094.0   
2         3      18         3              3             3.0     5698779.0   
3         4      18         4              4             4.0     5707797.0   
4         5      18         5              1             5.0     5708630.0   

   statusId  
0         1  
1         1  
2         1  
3         1  
4         1

In [565]:
qualifying_df.drop(['number', 'q1', 'q2', 'q3', 'qualifyId'], axis=1, inplace=True)
qualifying_df.rename(columns={'position': 'qualifying_position'}, inplace=True)

print(qualifying_df.dtypes)
qualifying_df.head()

raceId                 int64
driverId               int64
constructorId          int64
qualifying_position    int64
dtype: object


raceId  driverId  constructorId  qualifying_position
0      18         1              1                    1
1      18         9              2                    2
2      18         5              1                    3
3      18        13              6                    4
4      18         2              2                    5

In [566]:
lap_times_df.drop(['time', 'lap', 'position'], axis=1, inplace=True)
lap_times_df.rename(columns={'milliseconds': 'lap_time_milliseconds'}, inplace=True)

print(lap_times_df.dtypes)
lap_times_df.head()

raceId                   int64
driverId                 int64
lap_time_milliseconds    int64
dtype: object


raceId  driverId  lap_time_milliseconds
0     841        20                  98109
1     841        20                  93006
2     841        20                  92713
3     841        20                  92803
4     841        20                  92342

In [567]:
pit_stops_df.drop(['milliseconds', 'time', 'lap'], axis=1, inplace=True)
pit_stops_df.rename(columns={'duration': 'stop_duration', 'stop':'pit_stop'}, inplace=True)

pit_stops_df.stop_duration = pd.to_numeric(pit_stops_df.stop_duration, errors='coerce')
print(pit_stops_df.dtypes)
pit_stops_df.head()

raceId             int64
driverId           int64
pit_stop           int64
stop_duration    float64
dtype: object


raceId  driverId  pit_stop  stop_duration
0     841       153         1         26.898
1     841        30         1         25.021
2     841        17         1         23.426
3     841         4         1         23.251
4     841        13         1         23.842

In [568]:
driver_standings_df.drop(['position','positionText', 'wins', 'driverStandingsId'], axis=1, inplace=True)
driver_standings_df.rename(columns={'points': 'driver_points'}, inplace=True)

print(driver_standings_df.dtypes)
driver_standings_df.head()

raceId             int64
driverId           int64
driver_points    float64
dtype: object


raceId  driverId  driver_points
0      18         1           10.0
1      18         2            8.0
2      18         3            6.0
3      18         4            5.0
4      18         5            4.0

In [569]:
races_df.drop(['date','time', 'round','url', 'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date', 'sprint_time'], axis=1, inplace=True)
races_df.rename(columns={'name': 'circuit_name'}, inplace=True)

print(races_df.dtypes)
#filtered_races_df = races_df[races_df['year'] >= 2020]
#filtered_races_df.head()

raceId           int64
year             int64
circuitId        int64
circuit_name    object
dtype: object


In [570]:
constructors_df.drop(['url', 'nationality', 'constructorRef'], axis=1, inplace=True)
constructors_df.rename(columns={'name': 'constructor_name'}, inplace=True)

print(constructors_df.dtypes)
constructors_df.head()

constructorId        int64
constructor_name    object
dtype: object


constructorId constructor_name
0              1          McLaren
1              2       BMW Sauber
2              3         Williams
3              4          Renault
4              5       Toro Rosso

In [571]:
print(status_df.dtypes)
status_df.head()

statusId     int64
status      object
dtype: object


statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [572]:
races_years = races_df['year'].unique()

lap_times_years = pd.merge(lap_times_df, races_df, on='raceId')['year'].unique()
pit_stops_years = pd.merge(pit_stops_df, races_df, on='raceId')['year'].unique()
qualifying_years = pd.merge(qualifying_df, races_df, on='raceId')['year'].unique()

races_years.sort(), lap_times_years.sort(), pit_stops_years.sort(), qualifying_years.sort()

(races_years, lap_times_years, pit_stops_years, qualifying_years)

(array([1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
        1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
        1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
        1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
        1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
        2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
        2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]),
 array([1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
        2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
        2018, 2019, 2020, 2021, 2022, 2023, 2024]),
 array([2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
        2022, 2023, 2024]),
 array([1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
        2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
        2016, 2017, 2018, 2019, 2020, 2021

In [573]:
# merge datasets together

merge1_df = pd.merge(results_df, races_df, on='raceId', how='inner')
merge1_df = merge1_df.drop_duplicates(subset=['raceId', 'driverId'])

merge2_df = pd.merge(merge1_df, constructors_df, on='constructorId', how='inner')
merge2_df = merge2_df.drop_duplicates(subset=['raceId', 'driverId'])

merge3_df = pd.merge(merge2_df, driver_standings_df, on=['driverId', 'raceId'], how='inner')
merge3_df = merge3_df.drop_duplicates(subset=['raceId', 'driverId'])

merge4_df = pd.merge(merge3_df, lap_times_df, on=['driverId', 'raceId'], how='inner')
merge4_df = merge4_df.drop_duplicates(subset=['raceId', 'driverId'])

merge5_df = pd.merge(merge4_df, pit_stops_df, on=['driverId', 'raceId'], how='inner')
merge5_df = merge5_df.drop_duplicates(subset=['raceId', 'driverId'])

merge6_df = pd.merge(merge5_df, qualifying_df, on=['driverId', 'raceId'], how='inner')
merge6_df = merge6_df.drop_duplicates(subset=['raceId', 'driverId'])

final_combined_df = pd.merge(merge6_df, status_df, on='statusId', how='inner')
final_combined_df = final_combined_df.drop_duplicates(subset=['raceId', 'driverId'])

final_duplicates_check = final_combined_df.duplicated(subset=['raceId', 'driverId']).any()
final_duplicates_check

final_combined_df.drop(['constructorId_y'], axis=1, inplace=True)
final_combined_df.rename(columns={'constructorId_x': 'constructorId'}, inplace=True)

final_combined_df = final_combined_df[final_combined_df['status'] == 'Finished']
names = final_combined_df['year'].unique()
print(names)
display(final_combined_df)


[2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]


resultId  raceId  driverId  constructorId  final_position  milliseconds  \
0        20779     841        20              9             1.0     5370259.0   
1        20780     841         1              1             2.0     5392556.0   
2        20781     841       808              4             3.0     5400819.0   
3        20782     841         4              6             4.0     5402031.0   
4        20783     841        17              9             5.0     5408430.0   
...        ...     ...       ...            ...             ...           ...   
5292     26492    1131       825            210             8.0     5123153.0   
5293     26493    1131       817            215             9.0     5123967.0   
5294     26494    1131       842            214            10.0     5124564.0   
5295     26495    1131       844              6            11.0     5129854.0   
5296     26496    1131       839            214            12.0     5131123.0   

      statusId  year  circuitId           circuit_name constructor_name  \
0            1  2011          1  Australian Grand Prix         Red Bull   
1            1  2011          1  Australian Grand Prix          McLaren   
2            1  2011          1  Australian Grand Prix          Renault   
3            1  2011          1  Australian Grand Prix          Ferrari   
4            1  2011          1  Australian Grand Prix         Red Bull   
...        ...   ...        ...                    ...              ...   
5292         1  2024         70    Austrian Grand Prix     Haas F1 Team   
5293         1  2024         70    Austrian Grand Prix       RB F1 Team   
5294         1  2024         70    Austrian Grand Prix   Alpine F1 Team   
5295         1  2024         70    Austrian Grand Prix          Ferrari   
5296         1  2024         70    Austrian Grand Prix   Alpine F1 Team   

      driver_points  lap_time_milliseconds  pit_stop  stop_duration  \
0              25.0                  98109         1         22.603   
1              18.0                 100573         1         23.227   
2              15.0                 102835         1         24.535   
3              12.0                 106144         1         23.251   
4              10.0                 101467         1         23.426   
...             ...                    ...       ...            ...   
5292            5.0                  78826         1         21.518   
5293           11.0                  79507         1         21.502   
5294            6.0                  79109         1         21.431   
5295          150.0                  82085         1         31.917   
5296            3.0                  77703         1         22.291   

      qualifying_position    status  
0                       1  Finished  
1                       2  Finished  
2                       6  Finished  
3                       5  Finished  
4                       3  Finished  
...                   ...       ...  
5292                   12  Finished  
5293                   11  Finished  
5294                   13  Finished  
5295                    6  Finished  
5296                   10  Finished  

[2910 rows x 17 columns]